gbdp_projects = {
    "PRJNA707235": {
        "project_name": "University of California Consortium for the Earth "
                        "BioGenome Project (Cal-EBP)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJEB33226": {
        "project_name": "25 Genomes Project (Genome Data and Assemblies)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJEB51690": {
        "project_name": "Anopheles Reference Genomes Project (Data and "
                        "assemblies)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJEB80366": {
        "project_name": "AEGIS (Ancient Environmental Genomics Initiative for "
                        "Sustainability)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA1180976": {
        "project_name": "GBB Consortium",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA706349": {
        "project_name": "Catalan Initiative for the Earth BioGenome Project ("
                        "CBP)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA163993": {
        "project_name": "i5k initiative",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA293101": {
        "project_name": "Orestias ascotanensis Genome sequencing and assembly",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA682446": {
        "project_name": "Genome sequencing data and assemblies generated by "
                        "the Lewin Lab @ UC Davis Genome Center",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA706690": {
        "project_name": "CanSeq150 Project (Genome Data and Assemblies)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA911016": {
        "project_name": "Cephalopachus bancanus breed (not provided Genome "
                        "sequencing and assembly)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA1120070": {
        "project_name": "Lepus timidus genome sequencing",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA706923": {
        "project_name": "LOEWE Centre for Translational Biodiversity Genomics "
                        "(LOEWE-TBG)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA813333": {
        "project_name": "Canadian BioGenome Project (CBP)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJEB65317": {
        "project_name": "Earth BioGenome Project Norway (EBP-Nor)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA1020146": {
        "project_name": "Cetacean Genomes Project",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA1046164": {
        "project_name": "Ocean Genomes (Minderoo OceanOmics Centre at "
                        "University of the Western Australia)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA1157211": {
        "project_name": "Genome sequences and bird genomes assemblies for the "
                        "Danish Bird Genome (DBG) project under the B10K "
                        "consortium",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA714837": {
        "project_name": "Lilioid monocots core group genome sequencing and "
                        "assembly",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJEB40665": {
        "project_name": "DTOL",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJEB43510": {
        "project_name": "ERGA",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJEB43743": {
        "project_name": "ASG",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJEB49670": {
        "project_name": "Catalan Initiative for the Earth BioGenome Project ("
                        "CBP)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA312960": {
        "project_name": "200 Mammals",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA489243": {
        "project_name": "Vertebrate Genomes Project",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA555319": {
        "project_name": "USDA Agricultural Research Service’s Ag100Pest "
                        "Initiative",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA634441": {
        "project_name": "Monomorium pharaonis Genome sequencing and assembly",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA649812": {
        "project_name": "The Global Invertebrate Genomics Alliance (GIGA) "
                        "genomes and transcriptomes",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA712951": {
        "project_name": "ENDEMIXIT",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA720569": {
        "project_name": "The California Conservation Genomics Project (CCGP)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA785018": {
        "project_name": "Genome sequencing and assembly of primate species "
                        "Genome sequencing and assembly",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA811786": {
        "project_name": "African BioGenome Project (AfricaBP)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA844590": {
        "project_name": "Illinois EBP Pilot",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA512907": {
        "project_name": "DNA Zoo",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA734913": {
        "project_name": "Amphibalanus amphitrite (Genome Sequencing and "
                        "assembly)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA545868": {
        "project_name": "Bird 10000 Genomes (B10K) Project (Family phase)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJDB6260": {
        "project_name": "Elasmobranch shark genome evolution",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA489245": {
        "project_name": "Bat1K Project",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJNA707598": {
        "project_name": "Squalomix (Genome sequencing and assembly of "
                        "chondrichthyans)",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
    "PRJEB71705": {
        "project_name": "Project Psyche - Lepidopteran Genomes for Europe",
        "bucket_name": "prj-ext-prod-biodiv-data-in-gbdp",
    },
}
erga_projects = {
    "PRJEB40665": {
        "project_name": "DTOL",
        "bucket_name": "prj-ext-prod-biodiv-data-in-erga",
    },
    "PRJEB33226": {
        "project_name": "25 genomes",
        "bucket_name": "prj-ext-prod-biodiv-data-in-erga",
    },
    "PRJEB47985": {
        "project_name": "ERGA French node",
        "bucket_name": "prj-ext-prod-biodiv-data-in-erga",
    },
    "PRJEB49197": {
        "project_name": "ERGA Swiss node",
        "bucket_name": "prj-ext-prod-biodiv-data-in-erga",
    },
    "PRJEB61747": {
        "project_name": "ERGA BGE",
        "bucket_name": "prj-ext-prod-biodiv-data-in-erga",
    },
    "PRJEB66264": {
        "project_name": "ERGA Community Genomes",
        "bucket_name": "prj-ext-prod-biodiv-data-in-erga",
    },
    "PRJEB71705": {
        "project_name": "Project Psyche",
        "bucket_name": "prj-ext-prod-biodiv-data-in-erga",
    },
    "PRJEB64126": {
        "project_name": "ATLASea",
        "bucket_name": "prj-ext-prod-biodiv-data-in-erga",
    },
    "PRJEB49670": {
        "project_name": "CBP",
        "bucket_name": "prj-ext-prod-biodiv-data-in-erga",
    },
    "PRJEB47820": {
        "project_name": "ERGA Pilot",
        "bucket_name": "prj-ext-prod-biodiv-data-in-erga",
    },
    "PRJNA712951": {
        "project_name": "ENDEMIXIT",
        "bucket_name": "prj-ext-prod-biodiv-data-in-erga",
    },
}
dtol_projects = {
    "PRJEB40665": {
        "project_name": "DTOL",
        "bucket_name": "prj-ext-prod-biodiv-data-in-dtol",
    },
    "PRJEB33226": {
        "project_name": "25 genomes",
        "bucket_name": "prj-ext-prod-biodiv-data-in-dtol",
    },
}
asg_projects = {
    "PRJEB43743": {
        "project_name": "ASG",
        "bucket_name": "prj-ext-prod-biodiv-data-in-asg",
    }
}
